#!/usr/bin/env python3
"""run adapter – gaia.ingest.bounded.v1

Orchestrates the bounded OSM ingest run: reads normalized bindings,
writes the gaia-feature-store (per-feature JSON files) and the
gaia-tile-manifest (layer manifest candidate).

Usage:
  python3 adapters/run.py \\
      --bindings build/gaia/features/osm-feature-bindings.v1.json \\
      --out-store build/gaia/features \\
      --out-manifest build/gaia/tiles/tile-manifest.json
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[3]

ODBL_LICENSE_REF = "ODbL-1.0"
INGEST_TOOL_REF = "gaia-bounded-osm-ingest-runner@v1"


def sha256_object(data: Any) -> str:
    canonical = json.dumps(data, sort_keys=True, ensure_ascii=False)
    return f"sha256:{hashlib.sha256(canonical.encode()).hexdigest()}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run bounded OSM ingest: write feature store and tile manifest.")
    parser.add_argument("--bindings", required=True, help="Path to osm-feature-bindings JSON.")
    parser.add_argument("--out-store", required=True, help="Directory for per-feature JSON files.")
    parser.add_argument("--out-manifest", required=True, help="Path to write tile-manifest JSON.")
    args = parser.parse_args(argv)

    bindings_path = Path(args.bindings)
    if not bindings_path.is_absolute():
        bindings_path = ROOT / bindings_path
    if not bindings_path.exists():
        print(f"ERROR: bindings file not found: {bindings_path}", file=sys.stderr)
        return 1

    with bindings_path.open("r", encoding="utf-8") as fh:
        doc = json.load(fh)

    generated_at = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    bindings = doc.get("bindings", [])
    attribution = doc.get("attribution", {})
    classification = doc.get("classification", {})
    fixture_digest = doc.get("provenance", {}).get("fixture_digest", "")
    extract_ref = doc.get("extract_ref", "")
    envelope_id = doc.get("envelope_ref", "")

    # Write per-feature files to the feature store
    store_path = Path(args.out_store)
    if not store_path.is_absolute():
        store_path = ROOT / store_path
    store_path.mkdir(parents=True, exist_ok=True)

    h3_cells: set[str] = set()
    all_bboxes: list[list[float]] = []

    for b in bindings:
        osm_ref = b.get("osm_ref", {})
        osm_type = osm_ref.get("osm_type", "unknown")
        osm_id = osm_ref.get("osm_id", "unknown")
        feature_file = store_path / f"{osm_type}-{osm_id}.json"
        with feature_file.open("w", encoding="utf-8") as fh:
            json.dump(b, fh, indent=2, ensure_ascii=False)
            fh.write("\n")
        spatial = b.get("spatial", {})
        h3_cells.update(spatial.get("h3_cells", []))
        bbox = spatial.get("bbox")
        if isinstance(bbox, list) and len(bbox) == 4:
            all_bboxes.append(bbox)

    # Compute union bbox
    if all_bboxes:
        union_bbox = [
            min(b[0] for b in all_bboxes),
            min(b[1] for b in all_bboxes),
            max(b[2] for b in all_bboxes),
            max(b[3] for b in all_bboxes),
        ]
    else:
        union_bbox = [0, 0, 0, 0]

    # Write tile manifest
    manifest_filename = Path(args.out_manifest).name
    bindings_filename = bindings_path.name
    layer_id = envelope_id.replace("osm-source-envelope", "osm-layer-manifest-candidate")

    manifest = {
        "manifest_version": "v1",
        "layer_id": layer_id,
        "layer_type": "vector",
        "title": f"GAIA OSM Bounded Ingest Layer – {doc.get('envelope_ref', 'demo')}",
        "description": (
            "Bounded OSM ingest layer manifest candidate. "
            "Generated by run.py adapter. "
            "Not production tile-serving. Advisory only."
        ),
        "sources": [
            {
                "source_id": envelope_id,
                "source_type": "OpenStreetMap extract",
                "source_refs": [extract_ref, bindings_filename],
            }
        ],
        "tiles": {
            "url_template": "placeholder://tiles/gaia/osm-bounded/{z}/{x}/{y}.mvt",
            "min_zoom": 0,
            "max_zoom": 14,
            "format": "mvt",
        },
        "spatial": {
            "bbox": union_bbox,
            "h3_cells": sorted(h3_cells),
            "crs": "EPSG:4326",
        },
        "attribution": {
            "attribution_text": attribution.get("attribution_text", "© OpenStreetMap contributors"),
            "license_refs": [ODBL_LICENSE_REF],
            "source_urls": [attribution.get("source_url", "https://www.openstreetmap.org")],
        },
        "provenance": {
            "source_refs": [bindings_filename, extract_ref],
            "fixture_digest": fixture_digest,
            "runtime_refs": [INGEST_TOOL_REF],
            "created_at": generated_at,
        },
        "classification": classification,
    }
    manifest["provenance"]["content_hash"] = sha256_object(manifest["spatial"])

    manifest_path = Path(args.out_manifest)
    if not manifest_path.is_absolute():
        manifest_path = ROOT / manifest_path
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    with manifest_path.open("w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2, ensure_ascii=False)
        fh.write("\n")

    print(f"  OK  feature store written: {len(bindings)} features → {store_path}", file=sys.stderr)
    print(f"  OK  tile manifest → {manifest_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
