#!/usr/bin/env python3
"""Validate bounded OSM ingest runner outputs.

Proves that the outputs generated by scripts/ingest_bounded_osm_extract.py
satisfy GAIA provenance, attribution, identity, geometry, and source-receipt
digest-link requirements. This validator is fixture/proof-shaped; it does not
claim production live ingestion.

Validated artifacts (expected under examples/osm-bounded-ingest/):
  osm-feature-bindings.v1.json        – normalised GAIA feature binding set
  osm-source-receipt.v1.json          – source receipt with digest link
  osm-layer-manifest-candidate.v1.json – layer manifest candidate

Usage:
  python3 scripts/validate_bounded_osm_ingest.py

Exit codes:
  0 – all checks passed
  1 – one or more checks failed (ERROR: prefix on stdout)
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path
from typing import Any, Dict, Set, Tuple

ROOT = Path(__file__).resolve().parents[1]

FIXTURE_PATH = "fixtures/geospatial/osm-extract.bounded-lower-manhattan.sample.osm.json"
OUT_DIR = "examples/osm-bounded-ingest"
BINDINGS_PATH = f"{OUT_DIR}/osm-feature-bindings.v1.json"
RECEIPT_PATH = f"{OUT_DIR}/osm-source-receipt.v1.json"
LAYER_MANIFEST_PATH = f"{OUT_DIR}/osm-layer-manifest-candidate.v1.json"

ODBL_LICENSE_REF = "ODbL-1.0"
REQUIRED_OSM_ELEMENT_TYPES: Set[str] = {"node", "way", "relation"}


def fail(message: str) -> None:
    raise SystemExit(f"ERROR: {message}")


def load_json(path: Path) -> Dict[str, Any]:
    try:
        with path.open("r", encoding="utf-8") as fh:
            value = json.load(fh)
    except FileNotFoundError:
        fail(f"missing file: {path}")
    except json.JSONDecodeError as exc:
        fail(f"invalid JSON in {path}: {exc}")
    if not isinstance(value, dict):
        fail(f"expected top-level JSON object in {path}")
    return value  # type: ignore[return-value]


def sha256_file(path: Path) -> str:
    return f"sha256:{hashlib.sha256(path.read_bytes()).hexdigest()}"


# ---------------------------------------------------------------------------
# Input fixture checks
# ---------------------------------------------------------------------------


def check_input_fixture(fixture: Dict[str, Any], path: str) -> str:
    """Validate the input fixture and return its expected digest string."""
    required = ["input_version", "source", "extract_ref", "extracted_at", "region", "features", "attribution"]
    missing = [f for f in required if f not in fixture]
    if missing:
        fail(f"{path} missing required fields: {', '.join(missing)}")
    if fixture.get("source") != "OpenStreetMap":
        fail(f"{path} source must be 'OpenStreetMap'")
    features = fixture.get("features")
    if not isinstance(features, list) or not features:
        fail(f"{path} features must be a non-empty array")
    attr = fixture.get("attribution", {})
    if attr.get("license_ref") != ODBL_LICENSE_REF:
        fail(f"{path} attribution.license_ref must be '{ODBL_LICENSE_REF}'")
    return sha256_file(ROOT / path)


# ---------------------------------------------------------------------------
# Bindings checks
# ---------------------------------------------------------------------------


def check_bindings(doc: Dict[str, Any], path: str, fixture_digest: str) -> None:
    if doc.get("artifact_type") != "gaia.osm_bounded_source_adapter.bindings":
        fail(f"{path} artifact_type must be 'gaia.osm_bounded_source_adapter.bindings'")
    bindings = doc.get("bindings")
    if not isinstance(bindings, list) or not bindings:
        fail(f"{path} bindings must be a non-empty array")

    seen_types: Set[str] = set()
    seen_identities: Set[Tuple[str, str]] = set()

    for idx, binding in enumerate(bindings):
        bp = f"{path}:bindings[{idx}]"
        if not isinstance(binding, dict):
            fail(f"{bp} must be an object")
        for field in ("binding_version", "binding_id", "source", "osm_ref", "gaia_ref", "spatial", "attribution", "provenance", "classification"):
            if field not in binding:
                fail(f"{bp} missing required field '{field}'")

        # OSM identity and uniqueness
        osm_ref = binding.get("osm_ref", {})
        osm_type = osm_ref.get("osm_type")
        osm_id = osm_ref.get("osm_id")
        if osm_type not in {"node", "way", "relation"}:
            fail(f"{bp} osm_ref.osm_type must be 'node', 'way', or 'relation'; got {osm_type!r}")
        if not isinstance(osm_id, str) or not osm_id:
            fail(f"{bp} osm_ref.osm_id must be a non-empty string")
        seen_types.add(osm_type)
        identity = (osm_type, osm_id)
        if identity in seen_identities:
            fail(f"{path} duplicate OSM identity {identity} at index {idx}")
        seen_identities.add(identity)

        # Geometry/bbox presence
        spatial = binding.get("spatial", {})
        if not spatial.get("geometry_ref"):
            fail(f"{bp} spatial.geometry_ref must be non-empty")
        bbox = spatial.get("bbox")
        if not isinstance(bbox, list) or len(bbox) != 4:
            fail(f"{bp} spatial.bbox must be a 4-element array of numbers")
        if not all(isinstance(v, (int, float)) for v in bbox):
            fail(f"{bp} spatial.bbox values must all be numbers")
        crs = spatial.get("crs")
        if not isinstance(crs, str) or not crs:
            fail(f"{bp} spatial.crs must be a non-empty string")

        # H3 cells presence
        h3_cells = spatial.get("h3_cells")
        if not isinstance(h3_cells, list) or not h3_cells:
            fail(f"{bp} spatial.h3_cells must be a non-empty array")

        # Attribution / license
        attr = binding.get("attribution", {})
        if attr.get("license_ref") != ODBL_LICENSE_REF:
            fail(f"{bp} attribution.license_ref must be '{ODBL_LICENSE_REF}'")
        if not attr.get("attribution_text"):
            fail(f"{bp} attribution.attribution_text must be non-empty")

        # Provenance and fixture digest link
        prov = binding.get("provenance", {})
        if not prov.get("source_refs"):
            fail(f"{bp} provenance.source_refs must be non-empty")
        if prov.get("fixture_digest") != fixture_digest:
            fail(f"{bp} provenance.fixture_digest mismatch: expected {fixture_digest!r}, got {prov.get('fixture_digest')!r}")

    # All three OSM element types must be present
    missing_types = REQUIRED_OSM_ELEMENT_TYPES - seen_types
    if missing_types:
        fail(f"{path} bindings missing OSM element types: {', '.join(sorted(missing_types))}")

    # Top-level attribution
    top_attr = doc.get("attribution", {})
    if top_attr.get("license_ref") != ODBL_LICENSE_REF:
        fail(f"{path} top-level attribution.license_ref must be '{ODBL_LICENSE_REF}'")

    # Top-level provenance
    top_prov = doc.get("provenance", {})
    if not top_prov.get("source_refs"):
        fail(f"{path} top-level provenance.source_refs must be non-empty")
    if top_prov.get("fixture_digest") != fixture_digest:
        fail(f"{path} top-level provenance.fixture_digest mismatch: expected {fixture_digest!r}")


# ---------------------------------------------------------------------------
# Source receipt checks
# ---------------------------------------------------------------------------


def check_source_receipt(doc: Dict[str, Any], path: str, fixture_digest: str) -> None:
    for field in ("receipt_version", "receipt_id", "artifact_type", "fixture_path", "fixture_digest",
                  "extract_ref", "extracted_at", "generated_at", "element_summary", "output_refs",
                  "attribution", "classification"):
        if field not in doc:
            fail(f"{path} missing required field '{field}'")

    if doc.get("artifact_type") != "gaia.osm_bounded_ingest.source_receipt":
        fail(f"{path} artifact_type must be 'gaia.osm_bounded_ingest.source_receipt'")

    # Digest link
    if doc.get("fixture_digest") != fixture_digest:
        fail(f"{path} fixture_digest mismatch: expected {fixture_digest!r}, got {doc.get('fixture_digest')!r}")

    # Attribution
    attr = doc.get("attribution", {})
    if attr.get("license_ref") != ODBL_LICENSE_REF:
        fail(f"{path} attribution.license_ref must be '{ODBL_LICENSE_REF}'")
    if not attr.get("attribution_text"):
        fail(f"{path} attribution.attribution_text must be non-empty")

    # Element summary counts
    summary = doc.get("element_summary", {})
    for count_field in ("node_count", "way_count", "relation_count", "total_count"):
        if not isinstance(summary.get(count_field), int):
            fail(f"{path} element_summary.{count_field} must be an integer")
    expected_total = summary.get("node_count", 0) + summary.get("way_count", 0) + summary.get("relation_count", 0)
    if summary.get("total_count") != expected_total:
        fail(f"{path} element_summary.total_count {summary.get('total_count')} != sum of individual counts {expected_total}")

    # Output refs must be non-empty
    output_refs = doc.get("output_refs")
    if not isinstance(output_refs, list) or not output_refs:
        fail(f"{path} output_refs must be a non-empty array")

    # Route graph must be explicitly declared non-goal
    if "non-goal" not in doc.get("route_graph_status", ""):
        fail(f"{path} route_graph_status must declare route graph as non-goal")


# ---------------------------------------------------------------------------
# Layer manifest checks
# ---------------------------------------------------------------------------


def check_layer_manifest(doc: Dict[str, Any], path: str, fixture_digest: str) -> None:
    for field in ("manifest_version", "layer_id", "layer_type", "title", "sources", "tiles",
                  "spatial", "attribution", "provenance", "classification"):
        if field not in doc:
            fail(f"{path} missing required field '{field}'")

    # Spatial geometry/bbox
    spatial = doc.get("spatial", {})
    bbox = spatial.get("bbox")
    if not isinstance(bbox, list) or len(bbox) != 4:
        fail(f"{path} spatial.bbox must be a 4-element array")
    if not all(isinstance(v, (int, float)) for v in bbox):
        fail(f"{path} spatial.bbox values must all be numbers")
    h3_cells = spatial.get("h3_cells")
    if not isinstance(h3_cells, list) or not h3_cells:
        fail(f"{path} spatial.h3_cells must be a non-empty array")

    # Attribution
    attr = doc.get("attribution", {})
    if not attr.get("attribution_text"):
        fail(f"{path} attribution.attribution_text must be non-empty")
    if ODBL_LICENSE_REF not in attr.get("license_refs", []):
        fail(f"{path} attribution.license_refs must include '{ODBL_LICENSE_REF}'")

    # Provenance and digest link
    prov = doc.get("provenance", {})
    if not prov.get("source_refs"):
        fail(f"{path} provenance.source_refs must be non-empty")
    if prov.get("fixture_digest") != fixture_digest:
        fail(f"{path} provenance.fixture_digest mismatch: expected {fixture_digest!r}, got {prov.get('fixture_digest')!r}")

    # Sources non-empty
    sources = doc.get("sources")
    if not isinstance(sources, list) or not sources:
        fail(f"{path} sources must be a non-empty array")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> int:
    checks_passed = 0

    # 1. Validate input fixture and compute its digest
    fixture = load_json(ROOT / FIXTURE_PATH)
    fixture_digest = check_input_fixture(fixture, FIXTURE_PATH)
    print(f"  OK  input fixture: {FIXTURE_PATH}")
    print(f"  OK  fixture digest: {fixture_digest}")
    checks_passed += 1

    # 2. Validate feature bindings output
    bindings_doc = load_json(ROOT / BINDINGS_PATH)
    check_bindings(bindings_doc, BINDINGS_PATH, fixture_digest)
    print(f"  OK  {BINDINGS_PATH}")
    checks_passed += 1

    # 3. Validate source receipt output
    receipt_doc = load_json(ROOT / RECEIPT_PATH)
    check_source_receipt(receipt_doc, RECEIPT_PATH, fixture_digest)
    print(f"  OK  {RECEIPT_PATH}")
    checks_passed += 1

    # 4. Validate layer manifest candidate output
    manifest_doc = load_json(ROOT / LAYER_MANIFEST_PATH)
    check_layer_manifest(manifest_doc, LAYER_MANIFEST_PATH, fixture_digest)
    print(f"  OK  {LAYER_MANIFEST_PATH}")
    checks_passed += 1

    # 5. Cross-check: source receipt digest matches input fixture digest on disk
    actual_digest = sha256_file(ROOT / FIXTURE_PATH)
    if actual_digest != fixture_digest:
        fail(f"cross-check: digest of {FIXTURE_PATH} changed since validation started")
    print(f"  OK  source receipt digest cross-check passed")
    checks_passed += 1

    print(f"validated {checks_passed} bounded OSM ingest output checks "
          f"(input fixture, feature bindings, source receipt, layer manifest, digest cross-check)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
